apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      # volumes:
      #   - name: shared-volume
          # persistentVolumeClaim:
          #   claimName: shared-pvc
      containers:
        - name: pingpong
          image: dev1abhi/pingpong-app:1.3
          envFrom:
            - configMapRef:
               name: postgres-config
            - secretRef:
               name: postgres-secret
          # volumeMounts:
          #   - name: shared-volume
          #     mountPath: /shared

