apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
      containers:
        - name: log-writer
          image: dev1abhi/log-writer:1.0
          volumeMounts:
            - name: shared-logs
              mountPath: /shared

        - name: log-reader
          image: dev1abhi/log-reader:1.1
          volumeMounts:
            - name: shared-logs
              mountPath: /shared
