apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      volumes:
        - name: todo-data
          emptyDir: {}
      containers:
        - name: todo-backend
          image: dev1abhi/todo-backend:1.1
          volumeMounts:
            - name: todo-data
              mountPath: /app/data
          envFrom:
            - configMapRef:
                name: todo-backend-config

      
 