apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: exercises
type: Opaque
data:
  POSTGRES_USER: cGluZ3Bvbmc=        # "pingpong" (base64 encoded)
  POSTGRES_PASSWORD: cGFzc3dvcmQ=    # "password" (base64 encoded)
  POSTGRES_DB: cGluZ3Bvbmc=          # "pingpong" (base64 encoded)
