apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: project
type: Opaque
data:
  POSTGRES_USER: dG9kbw==          # "todo" (base64 encoded)
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # "password" (base64 encoded)
  POSTGRES_DB: dG9kbw==            # "todo" (base64 encoded)
